version: '3'

services:
  terminal:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7681:7681"
    volumes:
      - terminal-data:/home/user
    environment:
      - TERM=xterm-256color

volumes:
  terminal-data:

